cxx_compiler:         # [win]
  - vs2022            # [win]
c_compiler:           # [win]
  - vs2022            # [win]
c_stdlib_version:     # [osx]
  - "14.0"            # [osx]
libboost_headers:
  - '1.90'
